apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: "2025.4.0"
    helm:
      values: |
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          storageClass: ""
          size: 10Gi
        # defina um passcode p/ métricas se for usar monitoring
        monitoringPasscode: "change-me"
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true