spec:
  source:
    helm:
      values: |
        controller:
          admin:
            username: admin
            password: admin123
          serviceType: LoadBalancer
          installPlugins:
            - kubernetes
            - workflow-aggregator
            - git
            - configuration-as-code
